#!/bin/sh

cd $(dirname $0)

first=y

open() {
    if [ "$first" = "y" ]
    then
        tmux new-window "$1"
        first=n
    else
        tmux split-window "$1" \; select-layout tiled
    fi
}

for d in packages/*/tsconfig.json
do
    open "cd $(dirname $d); ../../node_modules/.bin/tsc -w"
done

for d in packages/*/rollup.config.js
do
    open "cd $(dirname $d); npx rollup -c -w"
done

tmux select-layout even-vertical
