#!/bin/sh
s6-svwait ../avahi-daemon
cd /usr/lib/node_modules/@syndicate-lang/server
DEBUG='syndicate/server:*' exec node lib/index.js \
     --http 8000 --monitor 8000 \
     --unix /var/run/syndicate.sock \
     --overlay test ws://test-server.syndicate-lang.org/
